import React,{useState} from 'react'
import {createRoot} from 'react-dom/client'
import {MemorialComposition,MemorialAppearanceEditor,normalizeAppearance} from './src/components/MemorialAppearance'
const hero=document.querySelector('.hero'),mount=document.createElement('div');mount.className='preview-react-mount';hero.append(mount);hero.classList.add('preview-react-active')
function App(){const[value,set]=useState(()=>normalizeAppearance(JSON.parse(localStorage.getItem('vspomin-memorial-appearance-demo')||'null'),'ru')),[edit,open]=useState(false),[lit,light]=useState(false),[people,contributors]=useState([]);window.openAppearance=()=>open(true);React.useEffect(()=>{const listener=e=>{light(e.detail.lit);contributors(e.detail.people||[])};window.addEventListener('memorial-demo-signs',listener);return()=>window.removeEventListener('memorial-demo-signs',listener)},[]);return edit?<MemorialAppearanceEditor name="Сачко Александр Антонович" dates="" settings={value} lang="ru" onClose={()=>open(false)} onSave={async v=>{set(v);localStorage.setItem('vspomin-memorial-appearance-demo',JSON.stringify(v))}}/>:<MemorialComposition name="Сачко Александр Антонович" dates="" settings={value} lang="ru" candleLit={lit} contributors={people}/>};createRoot(mount).render(<App/>);
import apiClient from './src/api/client'
import {MemorialSigns,MemorialSignsJournal} from './src/components/MemorialSigns'
const records=[];let hours=0,nextId=1;const base=Date.now(),visitorIds={anna:'ad63ca23-fc6f-4477-ad2d-f0d916727981',sergey:'bd63ca23-fc6f-4477-ad2d-f0d916727982',guest:'cd63ca23-fc6f-4477-ad2d-f0d916727983'}
apiClient.defaults.adapter=async config=>{const path=config.url,now=base+hours*3600000,active=records.filter(e=>e.expires>now);let data;if(config.method==='post'){const body=typeof config.data==='string'?JSON.parse(config.data):config.data,visitor=config.headers['X-Memorial-Visitor'];let item=active.find(e=>e.visitor===visitor&&e.kind===body.kind);if(!item){item={id:nextId++,kind:body.kind,variant:body.variant,display_name:body.display_name||'Анонимный посетитель',comment:body.comment||'',flower_type:body.flower_type||null,flower_color:body.flower_color||null,created_at:new Date(now).toISOString(),expires_at:new Date(now+86400000).toISOString(),expires:now+86400000,visitor};records.push(item)}data=item}else if(path.endsWith('/journal'))data={total:records.length,items:records.map(e=>({...e,expires_at:new Date(e.expires-hours*3600000).toISOString()}))};else data={items:active,candle_lit:active.some(e=>e.kind==='candle')};return {data,status:200,statusText:'OK',headers:{},config}}
const signsMount=document.createElement('section');signsMount.className='preview-real-signs';document.querySelector('.card').after(signsMount);document.querySelector('.demo-controls').style.display='none';
function SignsDemo(){const[journal,show]=useState(false),[revision,reload]=useState(0);React.useEffect(()=>{localStorage.setItem('memorialVisitor',visitorIds.anna);window.lightCandle=()=>signsMount.querySelector('.memorial-signs-actions button').click();window.openFlowers=()=>signsMount.querySelectorAll('.memorial-signs-actions button')[1].click()},[]);function time(h){hours=h;reload(v=>v+1)}return <><p>Демонстрация: знаки памяти не отправляются на сервер. Каждый посетитель оставляет свой знак на 24 часа.</p><div className="preview-sign-controls"><label>Посетитель <select aria-label="Посетитель" onChange={e=>{localStorage.setItem('memorialVisitor',visitorIds[e.target.value]);reload(v=>v+1)}}><option value="anna">Анна</option><option value="sergey">Сергей</option><option value="guest">Посетитель</option></select></label>{[0,12,24,25].map(h=><button key={h} onClick={()=>time(h)}>{h===0?'Сейчас':`Через ${h} ч`}</button>)}<button onClick={()=>show(true)}>Журнал владельца</button><button onClick={()=>{records.length=0;hours=0;reload(v=>v+1)}}>Сбросить знаки</button></div><MemorialSigns key={revision} memorialId="preview" lang="ru" onChange={v=>window.dispatchEvent(new CustomEvent('memorial-demo-signs',{detail:{lit:v.candle_lit,people:v.items.filter(e=>e.kind==='candle')}}))}/>{journal&&<MemorialSignsJournal memorialId="preview" lang="ru" onClose={()=>show(false)}/>}</>};createRoot(signsMount).render(<SignsDemo/>);
