#!/bin/bash

echo "🔍 Проверка логов Celery worker..."
echo ""
echo "Если worker запущен в фоне, логи можно увидеть только если он запущен в отдельном терминале."
echo ""
echo "Для просмотра логов в реальном времени, запустите worker в отдельном терминале:"
echo ""
echo "  cd backend"
echo "  source .venv/bin/activate"
echo "  celery -A app.workers.worker worker --loglevel=info"
echo ""
echo "Затем попробуйте анимировать фото и смотрите логи в этом терминале."
echo ""
echo "Там вы увидите:"
echo "  - Downloading image from: ..."
echo "  - Downloaded image, size: ... bytes"
echo "  - Uploading photo to HeyGen: ..."
echo "  - HeyGen upload response status: ..."
echo ""
echo "Если загрузка в HeyGen работает, ngrok НЕ нужен!"
echo "Если загрузка не работает, тогда нужен ngrok или S3."

