import { useEffect, useRef, useState } from 'react'
import './MemorialAppearance.css'
import spriteCenters from './appearanceSpriteCenters.json'
export const APPEARANCE_FONTS=[['serif','Архивный'],['sans','Простой'],['script','Рукописный'],['georgia','Georgia'],['playfair','Playfair Display'],['lora','Lora'],['cormorant','Cormorant Garamond'],['merriweather','Merriweather'],['pt_serif','PT Serif'],['roboto','Roboto']]
export const FLOWER_TYPES=[['carnations','Гвоздики'],['roses','Розы'],['chrysanthemums','Хризантемы'],['lilies','Лилии'],['asters','Астры'],['gerberas','Герберы']]
export const FLOWER_COLORS=[['red','Красные'],['white','Белые'],['yellow','Жёлтые'],['pink','Розовые'],['purple','Фиолетовые'],['blue','Синие']]
export const CANDLE_TYPES=[['classic','Классическая свеча'],['taper','Тонкая свеча'],['votive','Свеча в стакане'],['lantern','Фонарь'],['lampada','Лампадка'],['pillar','Свеча-столбик'],['beeswax','Восковая свеча'],['tea_light','Чайная свеча'],['memorial_glass','Мемориальная свеча'],['oil_lamp','Масляная лампа']]
export function appearanceDefaults(lang='ru'){return {quote:lang==='ru'?'Тепло, которое\nостаётся с нами':'Warmth that\nstays with us',flowers:'red_carnations',flower_type:'carnations',flower_color:'red',candle:'classic',font:'serif',font_size:28,font_name:'serif',font_size_name:48,font_dates:'sans',font_size_dates:16}}
export function normalizeAppearance(value,lang='ru'){const v={...appearanceDefaults(lang),...(value||{})};if(!v.flower_type)v.flower_type='carnations';if(!value?.flower_color)v.flower_color=value?.flowers==='white_carnations'?'white':'red';return Object.fromEntries(Object.entries(v).filter(([k])=>['quote','flowers','flower_type','flower_color','candle','font','font_size','font_name','font_size_name','font_dates','font_size_dates','layout','layout_mobile'].includes(k)))}
const desktopLayout={quote:{x:.64,y:.30,scale:1},flowers:{x:.82,y:.59,scale:1},candle:{x:.205,y:.82,scale:1},name:{x:.355,y:.48,scale:1},dates:{x:.355,y:.85,scale:1}}
const mobileLayout={quote:{x:.3,y:.65,scale:1},flowers:{x:.76,y:.67,scale:1},candle:{x:.285,y:.3,scale:1},name:{x:.68,y:.23,scale:1},dates:{x:.68,y:.425,scale:1}}
const kinds=['name','dates','quote','flowers','candle']
function useStageSize(ref){
 const [size,setSize]=useState({width:1000,height:300})
 useEffect(()=>{const el=ref.current;if(!el)return;const update=()=>{const r=el.getBoundingClientRect();setSize({width:r.width,height:r.height})};update();const observer=new ResizeObserver(update);observer.observe(el);return()=>observer.disconnect()},[ref])
 return size
}
function readableLayout(value,size,mobile){
 const result=Object.fromEntries(kinds.map(k=>[k,fittedLayout(value,k,size,mobile)]))
 if(!mobile){
  const name=result.name,quote=result.quote
  const nameRight=name.x*size.width+142.5*name.scale
  const quoteLeft=quote.x*size.width-122.5*quote.scale
  const overlapsVertically=Math.abs(name.y-quote.y)*size.height<83*name.scale+57.5*quote.scale
  if(overlapsVertically&&quoteLeft<nameRight+28&&quote.x>name.x){
   const available=size.width-nameRight-40
   if(available>=123){
    quote.scale=Math.min(quote.scale,available/245)
    quote.x=(nameRight+28+122.5*quote.scale)/size.width
   }else quote.y=Math.min(.85,name.y+(83*name.scale+57.5*quote.scale+16)/size.height)
  }
 }
 return result
}
function fittedLayout(value,kind,size,mobile){
 const defaults=mobile?mobileLayout:desktopLayout
 const source={...defaults[kind],...value?.[kind]}
 const dimensions=mobile?{name:[164,126],dates:[164,25],quote:[148,115],flowers:[142,142],candle:[58,58]}:{name:[285,166],dates:[285,28],quote:[245,115],flowers:[230,230],candle:[88,88]}
 const [w,h]=dimensions[kind],gutter=12
 const scale=Math.max(.5,Math.min(source.scale,(size.width-gutter*2)/w,(size.height-gutter*2)/h))
 const hx=(w*scale/2+gutter)/Math.max(1,size.width),hy=(h*scale/2+gutter)/Math.max(1,size.height)
 return {...source,scale,x:Math.max(hx,Math.min(1-hx,source.x)),y:Math.max(hy,Math.min(1-hy,source.y))}
}

export function flowerLabel(type,color,lang='ru'){return lang==='ru'?`${FLOWER_COLORS.find(e=>e[0]===color)?.[1]||color} ${FLOWER_TYPES.find(e=>e[0]===type)?.[1]?.toLowerCase()||type}`:`${color} ${type}`}
export function candleLabel(variant,lang='ru'){return lang==='ru'?(CANDLE_TYPES.find(e=>e[0]===variant)?.[1]||variant):variant.replaceAll('_',' ')}
export function FlowerArtwork({type='carnations',color='red'}){const row=Math.max(0,FLOWER_TYPES.findIndex(e=>e[0]===type)),col=Math.max(0,FLOWER_COLORS.findIndex(e=>e[0]===color));return <span className="appearance-real-flowers appearance-flower-sprite" role="img" aria-label={flowerLabel(type,color)} style={{backgroundPosition:`${col*20}% ${row*20}%`,transform:`translate(${spriteCenters.flowers[row*6+col][0]}%,${spriteCenters.flowers[row*6+col][1]}%) scale(.82)`}}/>}
export function MemorialCandle({variant='classic'}){if(variant==='none')return null;const index=Math.max(0,CANDLE_TYPES.findIndex(e=>e[0]===variant)),flameY={classic:34,taper:4,votive:45,lantern:60,lampada:55,pillar:8,beeswax:7,tea_light:42,memorial_glass:49,oil_lamp:14}[variant]||34;return <span className={`appearance-candle appearance-candle-sprite appearance-candle-${variant}`} style={{backgroundPosition:`${(index%5)*25}% ${index>=5?100:0}%`,transform:`translate(${spriteCenters.candles[index][0]}%,${spriteCenters.candles[index][1]}%) scale(.85)`}} aria-hidden="true"><svg className="appearance-sprite-flame" style={{top:`${flameY}%`}} viewBox="0 0 20 35"><path d="M10 35C-5 24 8 10 10 0C11 11 26 23 10 35" fill="#ffcb6f"/><path d="M10 32C4 25 10 16 10 12C12 21 17 26 10 32" fill="#fff0b0"/></svg></span>}
function fontInfo(v,kind){return {font:v[kind==='name'?'font_name':kind==='dates'?'font_dates':'font']||'serif',size:v[kind==='name'?'font_size_name':kind==='dates'?'font_size_dates':'font_size']||(kind==='name'?48:kind==='dates'?16:28)}}
function actionBy(name,kind,lang){if(lang!=='ru')return name?`${kind==='flowers'?'Left by':'Lit by'} ${name}`:'Anonymous visitor';if(!name||/Аноним|Anonymous/i.test(name))return kind==='flowers'?'Оставлено анонимно':'Зажжено анонимно';return `${/[ая]$/i.test(name)?(kind==='flowers'?'Оставила':'Зажгла'):(kind==='flowers'?'Оставил':'Зажёг')} ${name}`}
export function signDescription(sign,lang='ru'){const label=sign.kind==='flowers'?flowerLabel(sign.flower_type||'carnations',sign.flower_color||(sign.variant==='white_carnations'?'white':'red'),lang):candleLabel(sign.variant,lang);return `${label}. ${actionBy(sign.display_name,sign.kind,lang)}`}
export function MemorialComposition({settings,lang,candleLit=true,contributors=[],name='',dates=''}){const v=normalizeAppearance(settings,lang),stage=useRef(null),size=useStageSize(stage),mobile=size.width<600;return <div ref={stage} className={`appearance-stage${mobile?' appearance-mobile':''}`}>{kinds.map(kind=>{const d=readableLayout(v.layout,size,false)[kind],m=readableLayout(v.layout_mobile,size,true)[kind],f=fontInfo(v,kind);let title=kind==='flowers'?`${flowerLabel(v.flower_type,v.flower_color,lang)} · ${lang==='ru'?'Оформление семьи':'Family decoration'}`:contributors.length?contributors.map(e=>signDescription(e,lang)).join('\n'):`${candleLabel(v.candle,lang)} · ${lang==='ru'?'Оформление семьи':'Family decoration'}`;return <div key={kind} className={`appearance-item appearance-item-${kind}${kind==='candle'&&!candleLit?' appearance-item-unlit':''}`} style={{'--item-x':`${d.x*100}%`,'--item-y':`${d.y*100}%`,'--item-scale':d.scale,'--mobile-x':`${m.x*100}%`,'--mobile-y':`${m.y*100}%`,'--mobile-scale':m.scale}}>{kind==='name'?<h1 className={`appearance-display-name appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}}>{name}</h1>:kind==='dates'?<p className={`appearance-display-dates appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}}>{dates}</p>:kind==='quote'?<p className={`appearance-editable-quote appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}}>{v.quote}</p>:kind==='flowers'?v.flowers!=='none'&&<button type="button" className="appearance-art-button" title={title} aria-label={title}><FlowerArtwork type={v.flower_type} color={v.flower_color}/><span className="appearance-tooltip">{title}</span></button>:v.candle!=='none'&&<button type="button" className="appearance-art-button" title={title} aria-label={title}><MemorialCandle variant={contributors.at(-1)?.variant||v.candle}/><span className="appearance-tooltip">{title}{contributors.map(e=><span key={e.id}><br/>{e.comment}<br/>{new Date(e.created_at).toLocaleString(lang==='ru'?'ru-RU':'en-US')}</span>)}</span></button>}</div>})}</div>}
export function MemorialAppearanceEditor({settings,lang,onClose,onSave,name='',dates=''}){
 const[draft,setDraft]=useState(()=>normalizeAppearance(settings,lang)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,select]=useState('quote'),[guides,setGuides]=useState([])
 const stage=useRef(null),drag=useRef(null),ru=lang==='ru',size=useStageSize(stage),mobile=size.width<600,key=mobile?'layout_mobile':'layout'
 const layout=readableLayout(draft[key],size,mobile)
 function position(kind,change,snap=false){const box=stage.current.getBoundingClientRect(),el=stage.current.querySelector(`[data-kind="${kind}"]`),rect=el.getBoundingClientRect(),baseW=rect.width/layout[kind].scale,baseH=rect.height/layout[kind].scale,next={...layout[kind],...change};next.scale=Math.max(.5,Math.min(2,next.scale,box.width/baseW,box.height/baseH));const px=Math.min(.5,(baseW*next.scale/2+12)/box.width),py=Math.min(.5,(baseH*next.scale/2+12)/box.height),lines=[];if(snap){for(const axis of ['x','y']){const limit=axis==='x'?box.width:box.height,half=axis==='x'?px:py,candidates=[0,.5,1];for(const other of kinds.filter(k=>k!==kind)){const r=stage.current.querySelector(`[data-kind="${other}"]`).getBoundingClientRect(),a=axis==='x'?(r.left-box.left)/limit:(r.top-box.top)/limit,size=axis==='x'?r.width/limit:r.height/limit;candidates.push(a,a+size/2,a+size)}let best=null,dist=8/limit;for(const target of candidates)for(const ownOffset of [-half,0,half]){const difference=Math.abs(next[axis]+ownOffset-target);if(difference<dist){dist=difference;best={position:target-ownOffset,line:target}}}if(best){next[axis]=best.position;lines.push({axis,value:best.line})}}}next.x=Math.max(px,Math.min(1-px,next.x));next.y=Math.max(py,Math.min(1-py,next.y));setGuides(lines);setDraft(v=>({...v,[key]:{...layout,[kind]:next}}))}
 function begin(e,kind,resize=false){if(busy||kind!==selected)return;if(!resize&&e.target.closest('button,input,textarea,select'))return;e.preventDefault();select(kind);drag.current={kind,resize,x:e.clientX,y:e.clientY,box:stage.current.getBoundingClientRect(),initial:layout[kind]};e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e){const d=drag.current;if(!d)return;if(d.resize)position(d.kind,{scale:Math.max(.5,Math.min(2,d.initial.scale+(e.clientX-d.x)/140))});else position(d.kind,{x:d.initial.x+(e.clientX-d.x)/d.box.width,y:d.initial.y+(e.clientY-d.y)/d.box.height},true)}
 function cycle(kind,direction){const options=kind==='flowers'?FLOWER_TYPES.map(e=>e[0]):[...CANDLE_TYPES.map(e=>e[0]),'none'],field=kind==='flowers'?'flower_type':'candle',current=options.indexOf(draft[field]);setDraft(v=>({...v,[field]:options[(current+direction+options.length)%options.length],...(kind==='flowers'?{flowers:'red_carnations'}:{})}))}
 async function save(){setBusy(true);setError('');try{await onSave({...draft,[key]:layout});onClose()}catch(e){setError(typeof e.response?.data?.detail==='string'?e.response.data.detail:(ru?'Не удалось сохранить.':'Could not save.'));setBusy(false)}}
 const textSelected=['quote','name','dates'].includes(selected),fontField=selected==='name'?'font_name':selected==='dates'?'font_dates':'font',sizeField=selected==='name'?'font_size_name':selected==='dates'?'font_size_dates':'font_size',sizeLimits=selected==='name'?[16,72]:selected==='dates'?[10,32]:[16,48]
 return <div className={`appearance-inline-editor${mobile?' appearance-mobile':''}`} ref={stage} role="region" aria-label={ru?'Редактор оформления':'Appearance editor'} onPointerMove={move} onPointerUp={()=>{drag.current=null;setGuides([])}} onPointerCancel={()=>{drag.current=null;setGuides([])}}>{guides.map((g,i)=><div key={i} className={`appearance-guide appearance-guide-${g.axis}`} style={g.axis==='x'?{left:`${g.value*100}%`}:{top:`${g.value*100}%`}}/>)}{kinds.map(kind=>{const f=fontInfo(draft,kind);return <div key={kind} data-kind={kind} tabIndex={selected===kind?0:-1} className={`appearance-edit-item appearance-edit-${kind}${selected===kind?' selected':''}`} style={{left:`${layout[kind].x*100}%`,top:`${layout[kind].y*100}%`,transform:`translate(-50%,-50%) scale(${layout[kind].scale})`}} onPointerDown={e=>begin(e,kind)} onFocus={()=>{}} onKeyDown={e=>{if(kind!==selected)return;const delta=e.shiftKey?.03:.01,changes={ArrowLeft:{x:layout[kind].x-delta},ArrowRight:{x:layout[kind].x+delta},ArrowUp:{y:layout[kind].y-delta},ArrowDown:{y:layout[kind].y+delta}};if(changes[e.key]&&!e.target.closest('textarea')){e.preventDefault();position(kind,changes[e.key],true)}}}>
 {kind==='quote'?<textarea readOnly={selected!=='quote'} tabIndex={selected==='quote'?0:-1} aria-label={ru?'Семейная фраза':'Family words'} maxLength={160} value={draft.quote} className={`appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}} onChange={e=>setDraft({...draft,quote:e.target.value})}/>:kind==='name'?<p className={`appearance-editor-name appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}}>{name}</p>:kind==='dates'?<p className={`appearance-editor-dates appearance-font-${f.font}`} style={{fontSize:f.size,'--text-size':`${f.size}px`}}>{dates|| (ru?'Даты не указаны':'No dates')}</p>:kind==='flowers'?draft.flowers==='none'?<span>{ru?'Без цветов':'No flowers'}</span>:<FlowerArtwork type={draft.flower_type} color={draft.flower_color}/>:draft.candle==='none'?<span>{ru?'Без свечи':'No candle'}</span>:<MemorialCandle variant={draft.candle}/>}
 {kind==='quote'&&selected===kind&&<span className="appearance-drag-label">{ru?'Переместить':'Move'}</span>}<span role="slider" tabIndex={0} aria-label={ru?'Размер элемента':'Element size'} aria-valuemin={.5} aria-valuemax={2} aria-valuenow={layout[kind].scale} className="appearance-resize" onPointerDown={e=>{e.stopPropagation();begin(e,kind,true)}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.stopPropagation();e.preventDefault();position(kind,{scale:Math.max(.5,Math.min(2,layout[kind].scale+(e.key==='ArrowRight'?.1:-.1)))})}}}>↘</span></div>})}
 {['flowers','candle'].includes(selected)&&!mobile&&<div className="appearance-cycle"><button type="button" aria-label={ru?'Предыдущий вариант':'Previous variant'} onClick={()=>cycle(selected,-1)}>‹</button><span>{selected==='flowers'?flowerLabel(draft.flower_type,draft.flower_color,lang):candleLabel(draft.candle,lang)}</span><button type="button" aria-label={ru?'Следующий вариант':'Next variant'} onClick={()=>cycle(selected,1)}>›</button></div>}<div className="appearance-editor-bar"><div className="appearance-selection-tabs">{kinds.map(k=><button type="button" key={k} aria-pressed={selected===k} onClick={()=>select(k)}>{({name:'Имя',dates:'Даты',quote:'Фраза',flowers:'Цветы',candle:'Свеча'})[k]}</button>)}</div><span>{ru?({name:'Имя',dates:'Даты',quote:'Фраза',flowers:'Цветы',candle:'Свеча'}[selected]):selected}</span>{textSelected&&<><label>{ru?'Шрифт':'Font'} <select aria-label={ru?'Шрифт':'Font'} value={draft[fontField]} disabled={busy} onChange={e=>setDraft({...draft,[fontField]:e.target.value})}>{APPEARANCE_FONTS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>{ru?'Размер':'Size'} <input aria-label={ru?'Размер шрифта':'Font size'} type="number" min={sizeLimits[0]} max={sizeLimits[1]} value={draft[sizeField]} disabled={busy} onChange={e=>setDraft({...draft,[sizeField]:Math.max(sizeLimits[0],Math.min(sizeLimits[1],+e.target.value))})}/></label></>}{selected==='flowers'&&<><select aria-label={ru?'Вид цветов':'Flower species'} value={draft.flower_type} disabled={busy} onChange={e=>setDraft({...draft,flower_type:e.target.value,flowers:'red_carnations'})}>{FLOWER_TYPES.map(([v,l])=><option key={v} value={v}>{ru?l:v}</option>)}</select><div className="appearance-color-control" role="group" aria-label="Цвет цветов">{FLOWER_COLORS.map(([v,l])=><button type="button" key={v} title={l} aria-label={l} aria-pressed={draft.flower_color===v} style={{backgroundColor:({red:'#8b2527',white:'#f4eee1',yellow:'#e5c960',pink:'#dca5b5',purple:'#a28bbe',blue:'#839dc5'})[v]}} onClick={()=>setDraft({...draft,flower_color:v})}/>)}</div><button type="button" onClick={()=>setDraft({...draft,flowers:draft.flowers==='none'?'red_carnations':'none'})}>{draft.flowers==='none'?'Показать':'Скрыть'}</button></>}{selected==='candle'&&<select aria-label={ru?'Вид свечи':'Candle type'} value={draft.candle} onChange={e=>setDraft({...draft,candle:e.target.value})}>{CANDLE_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}<option value="none">{ru?'Без свечи':'No candle'}</option></select>}<button type="button" onClick={()=>setDraft(appearanceDefaults(lang))} disabled={busy}>{ru?'Сбросить':'Reset'}</button><button type="button" onClick={onClose} disabled={busy}>{ru?'Отмена':'Cancel'}</button><button type="button" onClick={save} disabled={busy}>{busy?'…':ru?'Сохранить':'Save'}</button>{error&&<span role="alert">{error}</span>}</div></div>
}
