import { useRef, useState, useId } from 'react'
import './MemorialAppearance.css'

export function appearanceDefaults(lang = 'ru') {
  return { font: 'serif', font_size: 28, quote: lang === 'ru' ? 'Тепло, которое\nостаётся с нами' : 'Warmth that\nstays with us', flowers: 'red_carnations', candle: 'classic' }
}
export function normalizeAppearance(value, lang = 'ru') {
  return Object.fromEntries(Object.entries({ ...appearanceDefaults(lang), ...(value || {}) }).filter(([key]) => ['quote','flowers','candle','font','font_size','layout','layout_mobile'].includes(key)))
}
export function MemorialCandle({ variant = 'classic' }) {
  const uid = useId().replace(/:/g, '')
  if (variant === 'none') return null
  if (variant === 'lampada') return <svg className="appearance-candle" viewBox="0 0 34 85" aria-hidden="true"><path className="appearance-flame" d="M17 45C10 39 15 32 17 26C19 33 24 40 17 45" fill="#ffd482"/><path d="M6 30H28L25 77H9Z" fill="#982d25" fillOpacity=".8" stroke="#d6b786"/><path d="M12 36H15V71H12Z" fill="#f4bb91" fillOpacity=".35"/><rect x="14" y="47" width="6" height="23" fill="#ead3a1"/><path d="M4 30L9 21H25L30 30ZM7 77H27V82H7Z" fill="#b49867"/><path d="M11 21V16H23V21" fill="none" stroke="#b49867" strokeWidth="2"/></svg>
  if (variant === 'classic') return <svg className="appearance-candle" viewBox="0 0 34 85" aria-hidden="true"><defs><linearGradient id={uid}><stop stopColor="#b59b70"/><stop offset=".45" stopColor="#f3e4bd"/><stop offset="1" stopColor="#a98e60"/></linearGradient></defs><path className="appearance-flame" d="M17 22C6 16 15 6 17 0C19 8 28 16 17 22" fill="#ffd482"/><rect x="10" y="24" width="14" height="58" rx="2" fill={`url(#${uid})`}/><ellipse cx="17" cy="82" rx="9" ry="2" fill="#9d804f"/></svg>
  return <svg className="appearance-candle" viewBox="0 0 34 85" aria-hidden="true"><defs><linearGradient id={uid}><stop stopColor="#b59b70"/><stop offset=".45" stopColor="#f3e4bd"/><stop offset="1" stopColor="#a98e60"/></linearGradient></defs>
    {variant === 'taper' ? <><path className="appearance-flame" d="M17 19C8 13 15 5 17 0C19 7 25 13 17 19" fill="#ffd482"/><path d="M14 22H20L22 77H12Z" fill={`url(#${uid})`}/><path d="M9 77H25L28 84H6Z" fill="#a48753"/></> : variant === 'lantern' ? <><path className="appearance-flame" d="M17 46C9 40 15 33 17 27C19 34 24 40 17 46" fill="#ffd482"/><path d="M7 29H27L25 75H9Z" fill="#c3a571" fillOpacity=".14" stroke="#a98c57"/><rect x="13" y="47" width="8" height="22" fill={`url(#${uid})`}/><path d="M5 29L11 20H23L29 29ZM7 75H27L29 81H5Z" fill="#9e814d"/><path d="M12 20V14Q17 5 22 14V20" fill="none" stroke="#a78b56" strokeWidth="2"/></> : <><path className="appearance-flame" d="M17 40C8 34 15 25 17 19C19 26 25 34 17 40" fill="#ffd482"/><rect x="6" y="42" width="22" height="37" rx="4" fill="#d6b985" fillOpacity=".4" stroke="#bda576"/><rect x="10" y="45" width="14" height="29" rx="2" fill={`url(#${uid})`}/></>}
  </svg>
}

const desktopLayout={quote:{x:.62,y:.32,scale:1},flowers:{x:.82,y:.64,scale:1},candle:{x:.205,y:.82,scale:1}}
const mobileLayout={quote:{x:.3,y:.68,scale:1},flowers:{x:.77,y:.75,scale:1},candle:{x:.36,y:.38,scale:1}}
const flowerVariants=['red_carnations','white_carnations','none']
const candleVariants=['classic','taper','votive','lampada','lantern','none']
const flowerLabels={red_carnations:'Красные гвоздики',white_carnations:'Белые гвоздики',none:'Без цветов'}
const candleLabels={classic:'Классическая свеча',taper:'Тонкая свеча',votive:'Свеча в стакане',lampada:'Лампадка',lantern:'Фонарь',none:'Без свечи'}
export function MemorialComposition({settings,lang,candleLit=true,contributors=[]}){
 const v=normalizeAppearance(settings,lang)
 return <div className={`appearance-stage appearance-font-${v.font||'serif'}`}>
  {['quote','flowers','candle'].map(kind=>{const d={...desktopLayout[kind],...v.layout?.[kind]},m={...mobileLayout[kind],...v.layout_mobile?.[kind]};const title=kind==='flowers'?`${flowerLabels[v.flowers]} · ${lang==='ru'?'Оформление семьи':'Family decoration'}`:`${candleLabels[v.candle]} · ${contributors.length?contributors.map(e=>e.display_name||(lang==='ru'?'Анонимный посетитель':'Anonymous visitor')).join(', '):(lang==='ru'?'Оформление семьи':'Family decoration')}`;return <div key={kind} className={`appearance-item appearance-item-${kind}${kind==='candle'&&!candleLit?' appearance-item-unlit':''}`} style={{'--item-x':`${d.x*100}%`,'--item-y':`${d.y*100}%`,'--item-scale':d.scale,'--mobile-x':`${m.x*100}%`,'--mobile-y':`${m.y*100}%`,'--mobile-scale':m.scale}}>
   {kind==='quote'?<p className="appearance-editable-quote" style={{fontSize:v.font_size||28}}>{v.quote}</p>:kind==='flowers'?v.flowers!=='none'&&<button type="button" className="appearance-art-button" title={title} aria-label={title}><img className={v.flowers==='white_carnations'?'appearance-white':''} src="/memorial-appearance/red-carnations.png" alt=""/><span className="appearance-tooltip">{title}</span></button>:v.candle!=='none'&&<button type="button" className="appearance-art-button" title={title} aria-label={title}><MemorialCandle variant={v.candle}/><span className="appearance-tooltip">{title}</span></button>}
  </div>})}
 </div>
}
export function MemorialAppearanceEditor({settings,lang,onClose,onSave}){
 const [draft,setDraft]=useState(()=>normalizeAppearance(settings,lang)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,select]=useState('quote')
 const stage=useRef(null),drag=useRef(null),ru=lang==='ru'
 const mobile=typeof window!=='undefined'&&window.matchMedia('(max-width:768px)').matches
 const key=mobile?'layout_mobile':'layout',defaults=mobile?mobileLayout:desktopLayout
 const layout=Object.fromEntries(Object.keys(defaults).map(k=>[k,{...defaults[k],...draft[key]?.[k]}]))
 function position(kind,change){const box=stage.current.getBoundingClientRect(),el=stage.current.querySelector(`[data-kind="${kind}"]`),rect=el.getBoundingClientRect(),baseW=rect.width/layout[kind].scale,baseH=rect.height/layout[kind].scale;const next={...layout[kind],...change};next.scale=Math.max(.5,Math.min(2,next.scale,box.width/baseW,box.height/baseH));const px=Math.min(.5,baseW*next.scale/box.width/2),py=Math.min(.5,baseH*next.scale/box.height/2);next.x=Math.max(px,Math.min(1-px,next.x));next.y=Math.max(py,Math.min(1-py,next.y));setDraft(v=>({...v,[key]:{...layout,[kind]:next}}))}
 function begin(e,kind,resize=false){if(e.target.closest('button,input,textarea,select'))return;e.preventDefault();select(kind);const box=stage.current.getBoundingClientRect();drag.current={kind,resize,x:e.clientX,y:e.clientY,box,initial:layout[kind]};e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e){const d=drag.current;if(!d)return;if(d.resize)position(d.kind,{scale:Math.max(.5,Math.min(2,d.initial.scale+(e.clientX-d.x)/140))});else{const el=stage.current.querySelector(`[data-kind="${d.kind}"]`),r=el.getBoundingClientRect(),padX=Math.min(.45,r.width/d.box.width/2),padY=Math.min(.45,r.height/d.box.height/2);position(d.kind,{x:Math.max(padX,Math.min(1-padX,d.initial.x+(e.clientX-d.x)/d.box.width)),y:Math.max(padY,Math.min(1-padY,d.initial.y+(e.clientY-d.y)/d.box.height))})}}
 function cycle(kind,direction){const options=kind==='flowers'?flowerVariants:candleVariants;const current=options.indexOf(draft[kind]);setDraft(v=>({...v,[kind]:options[(current+direction+options.length)%options.length]}))}
 async function save(){setBusy(true);setError('');try{await onSave(draft);onClose()}catch(e){setError(typeof e.response?.data?.detail==='string'?e.response.data.detail:(ru?'Не удалось сохранить.':'Could not save.'));setBusy(false)}}
 return <div className="appearance-inline-editor" ref={stage} role="region" aria-label={ru?'Редактор оформления':'Appearance editor'} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
  {['quote','flowers','candle'].map(kind=><div key={kind} data-kind={kind} tabIndex={0} className={`appearance-edit-item appearance-edit-${kind}${selected===kind?' selected':''}`} style={{left:`${layout[kind].x*100}%`,top:`${layout[kind].y*100}%`,transform:`translate(-50%,-50%) scale(${layout[kind].scale})`}} onPointerDown={e=>begin(e,kind)} onFocus={()=>select(kind)} onKeyDown={e=>{const delta=e.shiftKey?.03:.01;const changes={ArrowLeft:{x:Math.max(.1,layout[kind].x-delta)},ArrowRight:{x:Math.min(.9,layout[kind].x+delta)},ArrowUp:{y:Math.max(.1,layout[kind].y-delta)},ArrowDown:{y:Math.min(.9,layout[kind].y+delta)}};if(changes[e.key]&&!e.target.closest('textarea')){e.preventDefault();position(kind,changes[e.key])}}}>
   {kind==='quote'?<textarea aria-label={ru?'Семейная фраза':'Family words'} maxLength={160} value={draft.quote} className={`appearance-font-${draft.font||'serif'}`} style={{fontSize:draft.font_size||28}} onChange={e=>setDraft({...draft,quote:e.target.value})}/>:kind==='flowers'?draft.flowers==='none'?<span>{ru?'Без цветов':'No flowers'}</span>:<img className={draft.flowers==='white_carnations'?'appearance-white':''} src="/memorial-appearance/red-carnations.png" alt=""/>:draft.candle==='none'?<span>{ru?'Без свечи':'No candle'}</span>:<MemorialCandle variant={draft.candle}/>}
   <span className="appearance-drag-label">{ru?'Переместить':'Move'}</span>
   {kind!=='quote'&&<div className="appearance-cycle"><button type="button" aria-label={ru?'Предыдущий вариант':'Previous variant'} onClick={()=>cycle(kind,-1)}>‹</button><span>{ru?(kind==='flowers'?flowerLabels[draft.flowers]:candleLabels[draft.candle]):draft[kind]}</span><button type="button" aria-label={ru?'Следующий вариант':'Next variant'} onClick={()=>cycle(kind,1)}>›</button></div>}
   <span role="slider" tabIndex={0} aria-label={ru?'Размер элемента':'Element size'} aria-valuemin={.5} aria-valuemax={2} aria-valuenow={layout[kind].scale} className="appearance-resize" onPointerDown={e=>{e.stopPropagation();begin(e,kind,true)}} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.stopPropagation();e.preventDefault();position(kind,{scale:Math.max(.5,Math.min(2,layout[kind].scale+(e.key==='ArrowRight'?.1:-.1)))})}}}>↘</span>
  </div>)}
  <div className="appearance-editor-bar"><label>{ru?'Шрифт':'Font'} <select aria-label={ru?'Шрифт':'Font'} value={draft.font||'serif'} disabled={busy} onChange={e=>setDraft({...draft,font:e.target.value})}><option value="serif">{ru?'Книжный':'Serif'}</option><option value="sans">{ru?'Простой':'Sans'}</option><option value="script">{ru?'Рукописный':'Script'}</option></select></label><label>{ru?'Размер':'Size'} <input aria-label={ru?'Размер шрифта':'Font size'} type="number" min={16} max={48} value={draft.font_size||28} disabled={busy} onChange={e=>setDraft({...draft,font_size:Math.max(16,Math.min(48,+e.target.value))})}/></label><button type="button" onClick={()=>setDraft(appearanceDefaults(lang))} disabled={busy}>{ru?'Сбросить':'Reset'}</button><button type="button" onClick={onClose} disabled={busy}>{ru?'Отмена':'Cancel'}</button><button type="button" onClick={save} disabled={busy}>{busy?'…':ru?'Сохранить':'Save'}</button>{error&&<span role="alert">{error}</span>}</div>
 </div>
}
