import { useEffect, useRef, useState } from 'react'
import apiClient from '../api/client'
import {FLOWER_TYPES,FLOWER_COLORS,CANDLE_TYPES,FlowerArtwork,MemorialCandle,signDescription} from './MemorialAppearance'
import './MemorialSigns.css'
function visitorHeaders(){let id=localStorage.getItem('memorialVisitor');if(!id){id=crypto.randomUUID();localStorage.setItem('memorialVisitor',id)}return {'X-Memorial-Visitor':id}}
export function MemorialSigns({memorialId,lang,onChange}){
 const[items,setItems]=useState([]),[choice,setChoice]=useState(null),[name,setName]=useState(''),[comment,setComment]=useState(''),[flowerType,setFlowerType]=useState('carnations'),[flowerColor,setFlowerColor]=useState('red'),[candle,setCandle]=useState('classic'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState('')
 const requestVersion=useRef(0),picker=useRef(null),ru=lang==='ru'
 async function load(){const version=requestVersion.current;try{const{data}=await apiClient.get(`/memorials/${memorialId}/signs`);if(version!==requestVersion.current)return;setLoadError('');setItems(data.items);onChange?.(data)}catch{if(version===requestVersion.current)setLoadError(ru?'Не удалось загрузить знаки памяти.':'Could not load signs.')}}
 useEffect(()=>{requestVersion.current++;setItems([]);load();const timer=setInterval(load,60000);return()=>{requestVersion.current++;clearInterval(timer)}},[memorialId])
 async function submit(){setBusy(true);setError('');try{await apiClient.post(`/memorials/${memorialId}/signs`,{kind:choice,variant:choice==='candle'?candle:flowerType,...(choice==='flowers'?{flower_type:flowerType,flower_color:flowerColor}:{}),display_name:name.trim()||undefined,comment:comment.trim()||undefined},{headers:visitorHeaders()});await load();picker.current.close();setChoice(null)}catch(e){setError(typeof e.response?.data?.detail==='string'?e.response.data.detail:(ru?'Не удалось оставить знак памяти.':'Could not leave a sign of remembrance.'))}finally{setBusy(false)}}
 function open(kind){setChoice(kind);setError('');picker.current.showModal()}
 const flowers=items.filter(e=>e.kind==='flowers')
 return <section className="memorial-signs">{loadError&&<span role="alert">{loadError} <button type="button" onClick={load}>{ru?'Повторить':'Retry'}</button></span>}<div className="memorial-signs-actions"><button type="button" onClick={()=>open('candle')}>{ru?'Зажечь свечу':'Light a candle'}</button><button type="button" onClick={()=>open('flowers')}>{ru?'Оставить цветы':'Leave flowers'}</button><span>{ru?'На 24 часа':'For 24 hours'}</span></div><div className="memorial-visitor-signs">{flowers.slice(0,3).map(e=><button type="button" key={e.id} className="visitor-flower" title={signDescription(e,lang)} aria-label={signDescription(e,lang)}><FlowerArtwork type={e.flower_type||'carnations'} color={e.flower_color||(e.variant==='white_carnations'?'white':'red')}/><span className="visitor-tooltip">{signDescription(e,lang)}<br/>{e.comment&&<>{e.comment}<br/></>}{new Date(e.created_at).toLocaleString(ru?'ru-RU':'en-US')}<br/>{ru?'До':'Until'} {new Date(e.expires_at).toLocaleString(ru?'ru-RU':'en-US')}</span></button>)}{flowers.length>3&&<span>+{flowers.length-3}</span>}</div>
 <dialog ref={picker} className="signs-dialog" aria-labelledby="signs-title" onCancel={e=>{if(busy)e.preventDefault();else setChoice(null)}}><h2 id="signs-title">{choice==='candle'?(ru?'Зажечь свечу':'Light a candle'):(ru?'Оставить цветы':'Leave flowers')}</h2><p>{ru?'Знак памяти будет виден 24 часа. Повторное действие не продлевает срок. Имя и комментарий будут видны другим посетителям.':'Your sign stays visible for 24 hours. Repeating does not extend its duration. Your name and comment are public.'}</p>{choice==='flowers'?<><div className="signs-variant-grid" role="group" aria-label={ru?'Все виды цветов':'All flowers'}>{FLOWER_TYPES.flatMap(([v,l])=>FLOWER_COLORS.map(([color,colorLabel])=><button type="button" className="signs-variant-tile" key={`${v}-${color}`} aria-pressed={flowerType===v&&flowerColor===color} disabled={busy} onClick={()=>{setFlowerType(v);setFlowerColor(color)}}><FlowerArtwork type={v} color={color}/><span>{ru?`${colorLabel} ${l.toLowerCase()}`:`${color} ${v}`}</span></button>))}</div></>:<div className="signs-variant-grid" role="group" aria-label={ru?'Все свечи':'All candles'}>{CANDLE_TYPES.map(([v,l])=><button type="button" className="signs-variant-tile" key={v} aria-pressed={candle===v} disabled={busy} onClick={()=>setCandle(v)}><MemorialCandle variant={v}/><span>{ru?l:v}</span></button>)}</div>}<div className={`signs-choice-preview signs-choice-preview-${choice}`}>{choice==='flowers'?<FlowerArtwork type={flowerType} color={flowerColor}/>:<MemorialCandle variant={candle}/>}</div><label htmlFor="sign-name">{ru?'Ваше имя (необязательно)':'Your name (optional)'}</label><input id="sign-name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/><label htmlFor="sign-comment">{ru?'Комментарий (необязательно)':'Comment (optional)'}</label><textarea id="sign-comment" maxLength={500} value={comment} onChange={e=>setComment(e.target.value)} disabled={busy}/><small>{comment.length} / 500</small>{error&&<p role="alert">{error}</p>}<div><button type="button" onClick={()=>{picker.current.close();setChoice(null)}} disabled={busy}>{ru?'Отмена':'Cancel'}</button><button type="button" disabled={busy} onClick={submit}>{busy?'…':ru?'Оставить знак памяти':'Leave a sign'}</button></div></dialog></section>
}
export function MemorialSignsJournal({memorialId,lang,onClose}){
 const dialog=useRef(null),[data,setData]=useState(null),[offset,setOffset]=useState(0),[error,setError]=useState(''),ru=lang==='ru'
 useEffect(()=>{dialog.current.showModal()},[])
 useEffect(()=>{setData(null);setError('');apiClient.get(`/memorials/${memorialId}/signs/journal`,{params:{offset,limit:25}}).then(r=>setData(r.data)).catch(()=>setError(ru?'Не удалось загрузить журнал.':'Could not load the journal.'))},[offset,memorialId])
 return <dialog ref={dialog} className="signs-dialog signs-journal" aria-labelledby="journal-title" onCancel={onClose}><h2 id="journal-title">{ru?'Знаки памяти':'Signs of remembrance'}</h2>{error&&<p role="alert">{error}</p>}{!data&&!error?<p>{ru?'Загрузка…':'Loading…'}</p>:data&&<><div className="signs-table-wrap"><table><thead><tr><th>{ru?'Кто':'Who'}</th><th>{ru?'Знак':'Sign'}</th><th>{ru?'Комментарий':'Comment'}</th><th>{ru?'Когда':'When'}</th><th>{ru?'Состояние':'State'}</th></tr></thead><tbody>{data.items.map(e=><tr key={e.id}><td>{e.display_name||(ru?'Анонимный посетитель':'Anonymous visitor')}</td><td>{signDescription({...e,display_name:null},lang).split('. ')[0]}</td><td>{e.comment||'—'}</td><td>{new Date(e.created_at).toLocaleString(ru?'ru-RU':'en-US')}</td><td>{new Date(e.expires_at).getTime()>Date.now()?(ru?'Активно':'Active'):(ru?'Завершено':'Expired')}</td></tr>)}</tbody></table></div>{data.items.length===0&&<p>{ru?'Пока нет знаков памяти.':'No signs yet.'}</p>}<div><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>←</button><span>{data.total?offset+1:0}–{Math.min(offset+25,data.total)} / {data.total}</span><button disabled={offset+25>=data.total} onClick={()=>setOffset(offset+25)}>→</button></div></>}<button onClick={onClose}>{ru?'Закрыть':'Close'}</button></dialog>
}
